apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web

spec:
  containers:
  - name: fronted
    image: httpd:latest
    ports:
    - containerPort: 80
  - name: backend
    image: ubuntu:latest
    command: ['/bin/sh']
    args: ['-c', 'while true; do echo hello; sleep 10;done']